let x = exception(NameError, "Exceptional as ever.");
raise x;