try {
    5 + "Hello";
} catch NameError, TypeError, ValueError then {
    print "Caught";
}